on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        type: choice
        required: true
        default: "test"
        options:
          - "test"
          - "production"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app
        run: echo "Deploying app to ${{ inputs.environment }}"
